const base = process.env.REACT_APP_API_URL + '/api'

export const HOME_API = base + '/home'
export const CART_API = base + '/cart'
export const PRODUCT_API = base + '/products'
export const BRAND_API = base + '/brands'
export const MATERIAL_API = base + '/materials'
export const CATEGORY_API = base + '/categories'
export const SIZE_API = base + '/sizes'
export const AUTH_API = base + '/auth'
export const IMAGE_API = base + '/images'
export const PROFILE_API = base + '/images'
export const VOUCHER_API = base + '/vouchers'
export const PAYMENT_API = base + '/payments'
export const ORDER_API = base + '/orders'
export const ACCOUNT_API = base + '/account'
